import Link from "next/link";
import { FC } from "react";

import { SignInButton } from "@/features/auth";
import { SignInPageRoute } from "@/shared/config/routes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const SignUpPage: FC = () => {
  return (
    <>
      <div className="grid gap-2 text-center">
        <h1 className="text-3xl font-bold">Sign Up</h1>
      </div>
      <div className="grid gap-4">
        <SignInButton variant="outline" className="w-full">
          Login with Google
        </SignInButton>
      </div>
      <div className="mt-4 text-center text-sm">
        Don&apos;t have an account?{" "}
        <Link href={SignInPageRoute().url} className="underline">
          Sign in
        </Link>
      </div>
    </>
  );
};
