import { Metadata } from "next";
import Link from "next/link";
import { FC } from "react";

import { SignInButton } from "@/features/auth";
import { SignUpPageRoute } from "@/shared/config/routes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface SignInPageProps {
  searchParams: { [key: string]: string | string[] | undefined };
}

export const SignInPage: FC<SignInPageProps> = ({ searchParams }) => {
  const next = searchParams.next as string | undefined;
  return (
    <>
      <div className="grid gap-2 text-center">
        <h1 className="text-3xl font-bold">Sign In</h1>
      </div>
      <div className="grid gap-4">
        <SignInButton className="w-full" callbackUrl={next}>
          Login with Google
        </SignInButton>
      </div>
      <div className="mt-4 text-center text-sm">
        Don&apos;t have an account?{" "}
        <Link href={SignUpPageRoute().url} className="underline">
          Sign up
        </Link>
      </div>
    </>
  );
};
