import { Metadata } from 'next';
import { FC } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const PublicWaitinglistPage: FC = () => {
  return <>Waitinglist</>;
};
